### ISSUE TITLE
UTC conversion Incorrect

### ISSUE THREAD

**Issue by JasonK96** [midblue/timezone-bot#10]
Hi Guys,

I just wanted to let you know the UTC time conversions seem to be incorrect.

For London, it shows UTC+0 when it is supposed to be UTC+1
This also applies for Sweden as they should be UTC+2, I'm not sure if any other countries have been affected.

Thanks!
Jason

![image](https://user-images.githubusercontent.com/68155460/87225936-6bd04000-c388-11ea-9519-a96cd255457f.png)

**Comment by midblue** [comment]
Hi! Thanks for the heads up.
I have a follow up question: Are the times themselves right , and the listed number wrong?

The bot doesn't currently update its offset numbers for seasonal timezone shifts — it looks like according to [this](https://24timezones.com/time-zone/bst) that London is currently using British Summer Time. Is that accurate? 

If so, I'll look into making sure that the offset numbers match up with the current seasonal time shift.

Thanks!

**Comment by JasonK96** [comment]
Hey,

Thanks for getting back to me, that is correct, we are currently running on BST which is UTC +1 I believe. 

It is currently 02:26am here.

Thanks ,
Jason 😊

**Comment by midblue** [comment]
Well, fixing it is actually annoyingly hard (which is silly, since the actual time conversion works fine.
My hacky solution for now is just to remove the UTC code from displaying, since it didn't really add any new information anyway.
I'm calling it good enough for now!
