### ISSUE TITLE
Remove unused timezones from t!all

### ISSUE THREAD

**Issue by WarWraith** [midblue/timezone-bot#11]
We've got a multi-national server, and we've kicked several users from other timezones.

The downside is that we've now got multiple unused timezones that are still being tracked in t!all.

Is there any way to untrack those timezones?

I tried adding myself to the timezones and then removing myself, but that didn't work.

**Comment by midblue** [comment]
Hi! Thanks for the bug report! Can you post a screenshot so I can see exactly what you mean?

**Comment by WarWraith** [comment]
I've obscured usernames (obviously), but Moscow, India, Australian Central Time are all examples here.
![TZ-screenshot](https://user-images.githubusercontent.com/792439/89702945-623af780-d989-11ea-89db-1fe688e5a134.png)

**Comment by midblue** [comment]
I see! Should be fixed now, give it a shot.

**Comment by WarWraith** [comment]
Wow! Thanks. Excellent. Works perfectly.
