### ISSUE TITLE
Restrict getall query or output

### ISSUE THREAD

**Issue by tehgringe** [midblue/timezone-bot#12]
Hi there,
I manage a multi game server, and we have quite a few users on there. Only one section of channels has a timezone requirement (currently asking them to change nickname to include timezone). This is to arrange player fleet/group operations.

Is it possible to extend the t!users to include an optional parameter (default=all) to restrict the output to those users in the provided channel 
`t!users #fleet-team`

**Comment by midblue** [comment]
Hey! This isn't _exactly_ what you requested, but I added `t!all here` to get a channel-specific listing.
Please give it a shot and confirm it works for you.
