### ISSUE TITLE
Bot not responsive

### ISSUE THREAD

**Issue by CallMeTrey101** [midblue/timezone-bot#13]
After changing the prefix of the bot to "?" I could no longer use commands, I have kicked and invited the bot back many time but the bot is still unresponsive, please help.

**Comment by midblue** [comment]
Hi! I manually reset your server back to `t!`, and added new protections to stop you from breaking the regex with your prefix. Can you confirm the fix?

**Comment by CallMeTrey101** [comment]
Thx it worked🙂
