### ISSUE TITLE
New feature request - Extra arguments for !at

### ISSUE THREAD

**Issue by itsgaryk** [midblue/timezone-bot#17]
Add arguments for day and also member mention (if you do not know their location)

For example:

!at 10am tuesday Tokyo
!at 10am @Gary

**Comment by midblue** [comment]
(from discord, for my own notes)
t!at allow specifying a day name (or date). That way the output will show the correct day name for the time you are trying to convert (for a future event)
eg. It is currently Friday Philippine Time and you want to run the t!at to show what time it will be on Monday at 11pm Philippine Time  t!at Monday 11pm Philippine Time would change the day name from Friday to Monday, using Phillippine time as the reference day name.
 🌙Mon 11:00 PM - Philippine Time
 🌙Tue 1:00 AM - Australian Eastern Time

**Comment by midblue** [comment]
Added option to target a specific user, and also a specific day. Use it in the form `t!at (here?) (day?) (time) (location or username or @)`
