### ISSUE TITLE
Make changes to work with Heroku

### ISSUE THREAD

**Issue by SSmale** [midblue/timezone-bot#2]
There are some changes need to get this to work with Heroku, it needs to be a worker and it can't use file storage. I have made the changes to use google firebase and the url just needs adding to the env on the Heroku Dynos

**Comment by NNTin** [comment]
Proper Heroku implementation examples:  

https://github.com/NNTin/discord-twitter-bot    
https://github.com/vegeta897/d-zone/tree/heroku  
https://github.com/synzen/Discord.RSS   
https://github.com/NNTin/red-kun

If you test the Heroku deployment link all you need to do is [fill it out](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FNNTin%2Fdiscord-twitter-bot&template=https%3A%2F%2Fgithub.com%2FNNTin%2Fdiscord-twitter-bot). 

The red-kun example has a database attached (that automatically gets created with each Heroku app) so data storage is persistent. It also uses multiple buildpacks (Java and Python).  

Heroku is generally a bad place to host your bots. It is only good if you are providing this an an option for your users to host their own bot without any experience on how to host/run a program.

**Comment by SSmale** [comment]
It is a self host as it is specific to each discord server. 

I have already made the changes and I am using Firebase as the DB. see the attached pull request

**Comment by SSmale** [comment]
In the nicest possible way, it works and was only submitted here as others may have a similar use case. 

I found the original and didn’t know that Heroku doesn’t let you persist storage so made some changes to satisfy my needs. 

If you feel that you have a better solution please feel free to submit a PR as I have no interest in optimising this beyond my needs
