### ISSUE TITLE
t!setuser command does not work

### ISSUE THREAD

**Issue by cvuorinen** [midblue/timezone-bot#31]
I can set timezone for myself, I am admin of the server and have installed the bot, but when I try to assign timezones to other users nothing happens. I'm using the command like this `t!setuser @user City`

**Comment by midblue** [comment]
Yes, there's a bug on the Discord side at the moment. It should be fixed as soon as Discoed gets back to me about permissions. In the meantime, hang tight!

**Comment by midblue** [comment]
Hi! As of the latest commit we have a workaround: Just use @ mentions instead of text-based names and everything should work fine! Still waiting on a response from Discord.
