### ISSUE TITLE
Discord API issue?

### ISSUE THREAD

**Issue by Velocitractor00** [midblue/timezone-bot#33]
Hi, I just recently had to restart my own privately hosted instance of your bot - after moving house - and I am encountering an error with the 'UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body content: Must be 2000 or fewer in length' 

I don't know if this has come up because of changes to the discord api, or if there is anything I can do to fix this - apologies if you have already pushed a fix, I haven't kept up to date with all the commits here - as this instance was up for several months.

Graham

**Comment by Velocitractor00** [comment]
files mentioned in the error: 

discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15

node_modules/snekfetch/src/injex.js:215:21

internal/process/next_tick.js:68:7

thanks again

**Comment by midblue** [comment]
Yes, that would be an issue I've fixed previously. Was it with the info command? Or with a different one?

**Comment by Velocitractor00** [comment]
It was the all command, i have tried trimming my users down but I dont know
if thats ever going to fix the problem. I'll take a look later through your
commits if you know which one will fix it that might save me some time.

Thanks for the reply

P.s. I would swap to your public version but at the moment we share the bot
over a couple of different servers with overlapping communities and that
wouldn't be the same on the public one correct?

**Comment by midblue** [comment]
True, that would not work the same way on the public one.
I'm not sure what version of the code you're on, but that error is most likely coming from here:
https://github.com/midblue/timezone-bot/blob/master/actions/replyInChannel.js
Check it out and see if the part where it chops the message into 1990 character pieces is working properly on yours.

**Comment by Velocitractor00** [comment]
Ok, I'll check it out. Ty

**Comment by Velocitractor00** [comment]
Hi I just had some time to look at this, I feel like my bot version might be/must be pretty out of date, I dont have an actions folder or the file mentioned - would it be possible to import my existing users into the public version of your bot? - less than 100 but it would save me some hassle

thanks for the replies

G

**Comment by midblue** [comment]
Hi! I don't currently have any system to import users from separate instances into my live version of the bot. I don't want to make you start from scratch, so a solution might be to just find where in the older code it's sending more than 2000 characters at once, and break the message up in the same way that the file I posted is doing it. For now, I'm closing this, but I'll track any responses you make :)

**Comment by Velocitractor00** [comment]
I assumed it was just the sheer number of people I had signed up, and dramatically reduced it to no effect - I think I would need to setup your fix as in include or something, and I really dont have the time to deep dive into the js like I would want to - so for now I've gone with your public version of the bot - while I was cleaning my users I realised that a lot of them probably dont play on my server as much as they did when I first put your bot up there - self hosting your bot was a really fun way for me to get started on this journey, so I want to thank you for that! - hope the public bot is going well, and I'll let you know how I get on

Graham (Velocitractor)

**Comment by midblue** [comment]
I think you were on the right track! That would be the first thing I would check, too. Glad to hear you've at least settled on a solution. Hope everything goes well!
