### ISSUE TITLE
!at, !setuser, and !time functions not working for me

### ISSUE THREAD

**Issue by apalio** [midblue/timezone-bot#34]
I sincerely apologize if this is the wrong place to post this, but I didn't see any other type of support page. 

I added the bot to my server, and have used the !set and !timein functions successfully. However, when I enter either !at, !setuser, or !time followed by the correct syntax, nothing happens. I've tried doing it exactly as it shows in the example found in the !info, but nothing. I'm not sure if I'm doing something wrong, but if someone could offer any insight, I would really appreciate it. 

Also, not sure if I should open a separate issue for this, but I would like to remove the !users/all/here commands to work only for admin. I didn't see an option to change that, though I'm sure it's possible by modifying the source code (I'll admit I'm not too familiar with how to do that). My server has 2500 members and is growing rapidly, and I would rather not have some random person type !all and have it list 2000 people and their timezones. 

Please let me know if you have any questions for me. Thank you.

**Comment by midblue** [comment]
Hi! Yes, there have been some issues recently with the bot, and it's due to a Discord-side permissions issue. Until things can get sorted out on that side, I've pushed a version (5 minutes ago) that re-enables those commands, but without fuzzy search — you'll need to directly @ users to make the commands work.

**Comment by midblue** [comment]
Are you running your own copy of the bot? If so, it's fairly easy to restrict commands. Let me know your situation and I'll help as best I can.

**Comment by apalio** [comment]
@midblue The !at and !setuser are working for me now, thank you. 

I am not running my own copy of the bot. I'm not sure if it's possible to remove the !all/here/users from just my server. 

Also, I noticed that the bot has created multiple entries for time zones based off of how users put their time zone in when settings. This is resulting in the !at list being longer than necessary. [Here is an example.](https://imgur.com/a/rGvmt0d)

Also, is it possible for the !at command to show only the timezone of the person requesting it? Or to specify one? This would be better than listing all time zones if a person just wants to see what it is for them. For example, they type `!at 5pm GMT in EST` and it returns `At 5:00 PM in GMT, it will be 12:00 PM in EST.`
