### ISSUE TITLE
Australian Time zone

### ISSUE THREAD

**Issue by Prion-Ailurus** [midblue/timezone-bot#35]
List Melbourne and Sydney as Eastern Zone, even when they are in Eastern Daylight Savings. Therefor incorrectly groups them with Brisbane, which doesnt have Daylight Savings

**Comment by midblue** [comment]
I noticed that the Days for t!at have the wrong forumla for some zones.
like at t!at Sat 2pm GMT
AEST should be sunday
Dr TimToday at 4:45 PM
so weird it only affects the Australian time zones so far. in earlier testing i swear it was making a few countries wrong.
so it affects AEST and AET but not AWST
