### ISSUE TITLE
GIF Emotes Trigger <Here Function

### ISSUE THREAD

**Issue by TRoneX10** [midblue/timezone-bot#40]
GIF emotes are triggering the <here function and displaying the timezone list of those in the channel on accident

**Comment by midblue** [comment]
Hi, is your prefix `<`? That's the character that discord uses to wrap most embed links. The `here` command also responds to prefix+'h', so that's likely why that's happening.

**Comment by TRoneX10** [comment]
So what do you recommend I do? I’m assuming I should change the prefix but
not 100% sure if that’s what you’re saying.

-Trent

**Comment by midblue** [comment]
Yes!

**Comment by TRoneX10** [comment]
What would be safe prefixes to change to to prevent something like this
from happening again?

Also could you help explain the following commands for me? I'm not sure
what they do and when would be a time I would use them. I know each of them
has a short description but I didn't really understand them and figured I
could ask for help while I was talking with you. =)

   - <autorespond
   - <adminonly
   - <deletecommand
   - <deleteresponse
   - <suppresswarnings

-Trent

**Comment by midblue** [comment]
The prefix command will automatically stop you from setting it to anything too dangerous, I'll add angle brackets to the list. Try the command with something different and see if it accepts it.

As for those commands:
autorespond will toggle whether the bot will automatically reply to @s in your server with the user's timezone.
adminonly will make it so only people with ban powers or above can execute most commands. toggle it and re-run the `info` command to see what changes!
deleteresponse will automatically delete any message the timezone bot sends after 5 minutes.
suppresswarnings is for a subset of servers who were getting permissions errors, and the bot was spamming them with DMs about it. this command will make it so the bot will never DM admins about errors.

**Comment by TRoneX10** [comment]
What does the <deletecommand option do?

-Trent

**Comment by midblue** [comment]
delete command will delete the command.
i.e. if I type `t!info` it will delete my message and send the bot info
