### ISSUE TITLE
USA Arizona Time Zone not available

### ISSUE THREAD

**Issue by burtcasey** [midblue/timezone-bot#42]
Arizona has it's own Time Zone ,  when entering Phoenix or Arizona get assigned Mountain Time,  which is true half the year.  Arizona doesn't observe Daylight Savings Time.

**Comment by burtcasey** [comment]
ALSO:  I love your bot.

**Comment by midblue** [comment]
Hi! Thanks for using the bot!
Unfortunately, I don't manage the timezone database — I use Google's timezone API to get it. If there's something wrong with the data, there's really not anything I can do about it. Sorry!
