### ISSUE TITLE
List of time offsets or Time zone abbreviations option only

### ISSUE THREAD

**Issue by iNgeon** [midblue/timezone-bot#5]
Be able to set a timezone without revealing specifics.
Lots of users don't use due to privacy etc. but majority that are interested don't mind revealing the zones (UTC,EDT,PST,GMT etc) as per below. Is this currently possible ?

https://cdn.discordapp.com/attachments/386610998435381248/597854348076122142/Screenshot_2019-07-08_Time_Zone_Map.png

https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations

https://matall.in/posts/building-an-usable-timezone-selector/

https://momentjs.com/timezone/

**Comment by midblue** [comment]
You're absolutely right, I never really considered that. It's on the list for implementation.
A workaround (until there's a fix available) is to just use any other city in your timezone than the one you live in (i.e. "Toronto" instead of "New York City") to target the same time zone.

**Comment by midblue** [comment]
@iNgeon I'd love your input on this: I'm looking at a good way to let users pick a timezone without revealing locations, but I immediately run into the issue of overlapping timezone codes: i.e. IST is listed as Ireland, India, AND Israel. How would you suggest entering your timezone accurately without revealing your location?

**Comment by Velocitractor00** [comment]
https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568

you can use this list 👍  

we use it on another discord bot we have running, and its awesome for dealing with the timezones in abbreviated fashions

**Comment by midblue** [comment]
That list looks good, but I see a few issues: 
- most of them use location names anyway, which is what we're trying to avoid
- the actual timezone numbers aren't listed, which means we have to do a lookup anyway
- we could still run into the same timezone code overlap issues for the 3-letter acronym ones

Instead, how about if we simply add support for UTC+/- commands? like `!set UTC+4` or `!set utc-9`?
In fact, this may work already. Can someone confirm?

**Comment by Velocitractor00** [comment]
I have had mixed results when trying that 
![564465456564564](https://user-images.githubusercontent.com/36254031/62350055-712ad680-b4f9-11e9-9e3a-05b035bc06b8.PNG)

**Comment by midblue** [comment]
Got it. Sounds like we need to explicitly enable it.

**Comment by midblue** [comment]
@iNgeon I pushed a new update! All UTC commands should work now, i.e. 'UTC+2', 'UTC-11', etc.
