### ISSUE TITLE
Deletes messages really quickly.

### ISSUE THREAD

**Issue by kahedra** [midblue/timezone-bot#50]
https://user-images.githubusercontent.com/78300121/106381211-340d0200-6385-11eb-83df-0f88f3ca6d95.mp4

I have kicked and re invited the bot, still is doing this. On my friends server the bot doesn't have this issue, idk if its another bot interfering or what? But I'm out of ideas as to what could be causing this to happen, your bot is an amazing bot, but I can't read any of the messages.

**Comment by midblue** [comment]
Hi! Have you tried using `t!deleteresponse`? It can take a number argument that sets the number of seconds before it deletes.

**Comment by kahedra** [comment]
> Hi! Have you tried using `t!deleteresponse`? It can take a number argument that sets the number of seconds before it deletes.

That worked! Thank you, and have a great day! 😊
