### ISSUE TITLE
t!time IST returns wrong time

### ISSUE THREAD

**Issue by roperjonathan** [midblue/timezone-bot#63]
Hi there,

If you run the command t!time IST, you should see that the time is wrong by half an hour.

However, if you run t!time India, then it does return the correct time so it seems related to the specific timezone.

Can you let me know if you can replicate and fix?

Thanks

Jonathan

**Comment by midblue** [comment]
Fixed!

**Comment by roperjonathan** [comment]
Thanks for getting back to me about this.

However, on testing this, while this might be related to another issue but the times are still different. In fact now the time for t!time India also seems incorrect

For example, if I now write t!time India the time returns 16:09 whereas the time is actually 16:39

However, if I then write t!time IST, the time now returns 5:09am 

In fact if I use any timezone, the times seem to be wrong by many hours. Is there something I'm missing here?
