### ISSUE TITLE
Suggestion: Adding the use of universal slash /

### ISSUE THREAD

**Issue by joelm3103** [midblue/timezone-bot#64]
With the use of universal slashes from Discord, will this be implemented in the future without having to use the prefixes set?

**Comment by midblue** [comment]
Hi!
I've looked into it, and the way that it works on the backend would require a fair amount of rewriting. This is a feature that would be considered for version 2 of the bot, but as of today it's not on my list of action items.

**Comment by joelm3103** [comment]
Glad to know that you checked it out and it may be something in the future. Thanks for the quick update 😄.
