### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Velocitractor00** [midblue/timezone-bot#7]
Hey thanks for the bot first of all!

I'm inside my first day of using it, and I have a couple of small notes/feature requests 

I would like to request that the commands be shortened to one letter aliases, so `!time` would become `!t` - and so on.

I also have noticed a slight flaw, in that if someone has the place name in their discord name or nickname, it will attempt to pull that person instead of the time in the place

for example: `!time Glasgow` (which is where I live) - produces different usernames who have the word Glasgow in their nickname, instead of telling me the time in the City.

I thought at first this would be a few edge cases and I could probably work around it by changing their nicknames, but it turns out more people that I realised have their place name in their actual username.

is there a possibility to split the command, i.e. if I wanted to look up a user, individually I could use say a `!look` command 

the example on my server is a user called GlasgowAC 

so to look up the user I'd do `!look GlasgowAC` and to look up the place I'd do `!time Glasgow` so that the two arent conflated.

hope that made sense

thanks

Graham

**Comment by midblue** [comment]
Oh hey, you found a downside of having fuzzy search! That's a pretty good proposal. Maybe a !timein command would be more literal than !look which could be confusing.

I also like the hyper-short command idea, that's something I'm using on the newest bot I'm working on.

Both of these are on the to-do list.

**Comment by Velocitractor00** [comment]
awesome! the only other thing I noticed, was that I would like the ability to remove someone from the list, so say they leave the server (or in my case its a tester account that I dont want to be listed) 

would that be easy to add?

p.s. someone else I showed this to also pointed out that in the .js line 9, the bot ID is a set value, and isn't pulling from the `.env` file. tbh though, I left my version the way it was and its working, but I assume this would mean in theory that the bot could listen to itself.

**Comment by midblue** [comment]
Both of those are also worth fixing. It's also possible to automatically remove a user from the list on leaving the server.

**Comment by midblue** [comment]
Update is pushed! We should now have: 
- short commands
- !timein <location> command
- actual BOT_ID usage
- automatic removal from the list when a user leaves the server
- !removeme command to remove yourself from tracking

I didn't add a "remove other user" because then we need to get into admin checking etc. Does that work for you?

**Comment by Velocitractor00** [comment]
yes, thats AWESOME, thanks :D
