### ISSUE TITLE
Bug: t!at matches timezone with seemingly random user

### ISSUE THREAD

**Issue by zsawyer** [midblue/timezone-bot#70]
query: T!at Tue 7pm EST
responds: It doesn't look like [1stTN(Co.A)]Vol.Beefy has set a timezone for themselves yet.

![IMG_20210811_013610](https://user-images.githubusercontent.com/897208/128948410-a22dcf1a-ea90-4c79-b8cb-7f37b493991c.png)

**Comment by zsawyer** [comment]
Looking at the code I think a simple fix would be to reorder the evalutation of userOrLocation. 
Currently the logic first checks if a fuzzy match against a user is successful and THEN check against timezones and locations after:
1. user check
2. timezone check
2. location check


I suggest switching the logic to: 
1. timezone check
2. location check
3. user check

The reason is because I expect the fuzzy search to be broader than the city search. But if it is not 2. and 3. could be switched. 
The important part is that the "harder" lookups should come first.

**Comment by midblue** [comment]
The challenging thing about switching to that order is that the google location check almost ALWAYS returns something, even if the input is garbage.
We COULD switch the timezone check to be first, though, and I believe that would solve most of the problem.

**Comment by midblue** [comment]
The order switch is done! Calling this done for now.
