### ISSUE TITLE
Suggestions: Add support for time without colons

### ISSUE THREAD

**Issue by wrycu** [midblue/timezone-bot#73]
[24 hour time is often written without a colon](https://english.stackexchange.com/questions/384615/is-there-a-universal-format-for-24-hour-time), but is completely ignored if passed to the bot.  

Any chance you could add support for times without a colon?

![image](https://user-images.githubusercontent.com/4709746/132143510-0828766e-3924-4048-a152-3f179ec85aaf.png)

**Comment by midblue** [comment]
Fixed!

**Comment by wrycu** [comment]
Awesome, thank you!

**Comment by arknano** [comment]
i'm pictured in this screenshot and I thank you for your service

**Comment by midblue** [comment]
No problem!
By the way, it defaults to your set time now if you don't put one, so just `!at 1030` should do the trick if you're already set to Adelaide :)
